project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
    commonmark: default
    # --- New Settings from Image 2 ---
    grid:
      margin-width: 350px
    reference-location: margin
    citation-location: margin
  
  # Adds PDF support (from Image 2)
  pdf: default

# --- New Settings from Image 2 ---
execute:
  echo: fenced

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]